---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/Knappek/mongodbatlas-operator

steps:
- name: install_operator_sdk
  pull: always
  image: golang:1.12-alpine
  commands:
    - apk add -U git make curl
    - mkdir -p $GOPATH/bin
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    - go get -d github.com/operator-framework/operator-sdk/cmd/operator-sdk # This will download the git repository and not install it
    - cd $GOPATH/src/github.com/operator-framework/operator-sdk
    - git checkout master
    - make dep
    - make install
    - operator-sdk version
  when:
    event:
    - push
    - tag

- name: build_docker
  pull: always
  image: golang:1.12-alpine
  commands:
  - apk add -U make
  - make docker-build
  when:
    event:
    - push
    - tag

- name: push_docker
  image: plugins/docker
  pull: always
  settings:
    username: knappek
    password:
      from_secret: DOCKERHUB_PASSWORD
    repo: knappek/mongodbatlas-operator
    tag:
    - latest
  when:
    event:
    - push
    - tag

# - name: github
#   pull: default
#   image: plugins/github-release
#   settings:
#     files: "dist/*"
#   environment:
#     GITHUB_TOKEN:
#       from_secret: github_token
#   when:
#     event:
#     - tag
