---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/Knappek/mongodbatlas-operator

steps:
- name: build
  pull: always
  image: golang:1.12-alpine
  volumes:
  - name: go_bin
    path: /go/bin
  commands:
    - apk add -U make gcc
    - make build
  when:
    event:
    - push
    - tag

- name: docker
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: build/Dockerfile
    repo: knappek/mongodbatlas-operator
    tag:
    - latest
  when:
    event:
    - push

# - name: docker
#   pull: always
#   image: docker:18.09
#   volumes:
#   - name: go_bin
#     path: /go/bin
#   environment:
#     GOPATH: /go/
#   commands:
#   - export PATH=$PATH:/go/bin
#   - pwd 
#   - echo $GOPATH
#   - which dep
#   - apk add -U make
#   - make docker-build
#   when:
#     event:
#     - push
#     - tag

# volumes:
# - name: go_bin
#   temp: {}


# - name: push_docker
#   image: plugins/docker
#   pull: always
#   settings:
#     username: knappek
#     password:
#       from_secret: DOCKERHUB_PASSWORD
#     repo: knappek/mongodbatlas-operator
#     tag:
#     - latest
#   when:
#     event:
#     - push
#     - tag

# - name: github
#   pull: default
#   image: plugins/github-release
#   settings:
#     files: "dist/*"
#   environment:
#     GITHUB_TOKEN:
#       from_secret: github_token
#   when:
#     event:
#     - tag
