---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/Knappek/mongodbatlas-operator

steps:
- name: build
  pull: always
  image: golang:1.12-alpine
  commands:
    - apk add --update alpine-sdk
    - make build
    - make fmt
    - make lint
  when:
    event:
    - push
    - tag
    - pull_request

- name: docker
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: build/Dockerfile
    repo: knappek/mongodbatlas-operator
    tag:
    - latest
    - 0.0.1
  when:
    event:
    - tag

- name: release
  pull: default
  image: plugins/github-release
  settings:
    files: "build/_output/mongodbatlas-operator*"
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  when:
    event:
    - tag
