# permissions for end users to edit mongodbatlasclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodbatlascluster-editor-role
rules:
- apiGroups:
  - mongodbatlas.knappek.com
  resources:
  - mongodbatlasclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mongodbatlas.knappek.com
  resources:
  - mongodbatlasclusters/status
  verbs:
  - get
