# permissions for end users to view mongodbatlasclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodbatlascluster-viewer-role
rules:
- apiGroups:
  - mongodbatlas.knappek.com
  resources:
  - mongodbatlasclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mongodbatlas.knappek.com
  resources:
  - mongodbatlasclusters/status
  verbs:
  - get
