apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mongodbatlasprojects.knappek.com
spec:
  group: knappek.com
  names:
    kind: MongoDBAtlasProject
    listKind: MongoDBAtlasProjectList
    plural: mongodbatlasprojects
    singular: mongodbatlasproject
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            username:
              description: 'username is the username of an associated MongoDB Atlas Account. 
              It is used together with the apiKey to authenticate to the MongoDB Atlas API: More info: LINK'
              type: string
            orgId:
              description: 'orgId is the MongoDB Atlas Organisation ID (also known as 
              groupID. More info: LINK'
              properties:
                secretName:
                  type: string  
                key:
                  type: string
              type: object
            apiKey:
              description: 'apiKey is the API Key of a MongoDB Atlas User Account 
              which is used together with username to authenticate to the MongoDB Atlas API: More info: LINK'
              properties:
                secretName:
                  type: string  
                key:
                  type: string
              type: object
          required:
          - username
          - orgId
          - apiKey
          type: object
        status:
          properties:
            clusterCount:
              type: integer
            id: 
              type: string
            name: 
              type: string
            orgId:
              type: string
            status: 
              type: string
          required:
          - id
          - orgId
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
