apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mongodbatlasprojects.knappek.com
spec:
  group: knappek.com
  names:
    kind: MongoDBAtlasProject
    listKind: MongoDBAtlasProjectList
    plural: mongodbatlasprojects
    singular: mongodbatlasproject
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterCount:
              format: int64
              type: integer
            created:
              type: string
            id:
              type: string
            name:
              type: string
            orgId:
              type: string
            privateKey:
              properties:
                valueFrom:
                  properties:
                    secretKeyRef:
                      description: Selects a key of a secret in the CR's namespace
                      type: object
                  required:
                  - secretKeyRef
                  type: object
              required:
              - valueFrom
              type: object
            publicKey:
              type: string
          required:
          - publicKey
          - privateKey
          type: object
        status:
          properties:
            clusterCount:
              format: int64
              type: integer
            created:
              type: string
            id:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            name:
              type: string
            orgId:
              type: string
          required:
          - id
          - name
          - orgId
          - created
          - clusterCount
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
